(* generated by dune *)

(** @canonical Toyc_lib.Toyc_ast *)
module Toyc_ast = Toyc_lib__Toyc_ast

(** @canonical Toyc_lib.Toyc_codegen *)
module Toyc_codegen = Toyc_lib__Toyc_codegen

(** @canonical Toyc_lib.Toyc_lexer *)
module Toyc_lexer = Toyc_lib__Toyc_lexer

(** @canonical Toyc_lib.Toyc_parser *)
module Toyc_parser = Toyc_lib__Toyc_parser

(** @canonical Toyc_lib.Toyc_semantic *)
module Toyc_semantic = Toyc_lib__Toyc_semantic
